[[Typst]]
arch = "aarch64"
git-tree-sha1 = "28fcdcab2d44611ea96f4d1056fd83e52d29f998"
os = "macos"

    [[Typst.download]]
    sha256 = "149f91486ea9a611bffbc017cc4efe2a63e12e1bb3eb30fab2f3a3934ebd6928"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.11.1+0/Typst.v0.11.1.aarch64-apple-darwin.tar.gz"
[[Typst]]
arch = "aarch64"
git-tree-sha1 = "ac057ba724ff8fd5e59707722921c69a2353983e"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "d7db2074eca8680a12de8cb04c4b41b31a16fed3a17509eaeed169b08f8efd65"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.11.1+0/Typst.v0.11.1.aarch64-linux-gnu.tar.gz"
[[Typst]]
arch = "aarch64"
git-tree-sha1 = "74edc250846e1b61c1c06083c0f59b1ff2dda486"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "ef5ba13053cebaedb840dbe9865e653b12576c6a8b77bbb5552573d9067dd221"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.11.1+0/Typst.v0.11.1.aarch64-linux-musl.tar.gz"
[[Typst]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3f67aa2e9ced422cb15561faf0c889432533f548"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "0f92112edb9aebccc2469c7d8e20755bfb13d01797594146bf3335ab72fbfe8b"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.11.1+0/Typst.v0.11.1.armv6l-linux-gnueabihf.tar.gz"
[[Typst]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "89a37a4f9b7f0b0cf542e69d026dd175a444c91f"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "dcafb59ff4b2c5dbb347f86e962af302c42bdcc0517e14cf3aefc3e2852a5a6f"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.11.1+0/Typst.v0.11.1.armv6l-linux-musleabihf.tar.gz"
[[Typst]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9e77d102a38c9720dab80346f935bec99364c3d3"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "dae722a61bb46b897170b087116562dae702bb5e068edae562366fde4d9f8f7b"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.11.1+0/Typst.v0.11.1.armv7l-linux-gnueabihf.tar.gz"
[[Typst]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "79269a475189cebe338a261fa0ee8758ba91e9bf"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "bb401e77e2d72f393fd364bc2ef15bd6a9bc983123c8a70ccaee90e4e7335788"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.11.1+0/Typst.v0.11.1.armv7l-linux-musleabihf.tar.gz"
[[Typst]]
arch = "i686"
git-tree-sha1 = "47067bb3afc3ea0392c5b46468d8677f99e38cc2"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "b53f53e8e2f9634deab012eca29895a99434fbe3eeaec99af6a596872801329a"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.11.1+0/Typst.v0.11.1.i686-linux-gnu.tar.gz"
[[Typst]]
arch = "i686"
git-tree-sha1 = "9ffb8942038f28a0dbb86154e4e71a16e1eb2cfb"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "7996186717f5cae898dc3fd2051578ad4d3b26effc5d0b1541902c6884f19dd4"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.11.1+0/Typst.v0.11.1.i686-linux-musl.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "b0a6e7af5fbadaf64e05a4a072b670956a55fe19"
os = "macos"

    [[Typst.download]]
    sha256 = "338f84f3905742d5303e14fbeaf2c7f950a348be7127732fef15f4adec3d6129"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.11.1+0/Typst.v0.11.1.x86_64-apple-darwin.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "ca45f23a2658599f23ddfd410a22c03705dcdaba"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "a8274f5d7582d851b8f4659dd15f6146e32d937a06960a4efcc3a5b2cb4a2160"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.11.1+0/Typst.v0.11.1.x86_64-linux-gnu.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "40ea400a16e6ee9795db6397630c901788677de3"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "6fc0ab9b27690b2fd7f1b031d649350e0ace5e3e3e8c3f6f12816372b9b3428a"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.11.1+0/Typst.v0.11.1.x86_64-linux-musl.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "d310d227170414208d37a43370dafd7095b7af8d"
os = "freebsd"

    [[Typst.download]]
    sha256 = "416cbca463c07ae8d8c3af9c23aacc0a811e50e536ffbe69937b3e914fc6344b"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.11.1+0/Typst.v0.11.1.x86_64-unknown-freebsd.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "8160e4f6216e0ce642af118e2965c20f31460519"
os = "windows"

    [[Typst.download]]
    sha256 = "77c9320aa705038c8cd54f80cf02d9772a139f1f7d0802a59912257feb390eed"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.11.1+0/Typst.v0.11.1.x86_64-w64-mingw32.tar.gz"
