[[Typst]]
arch = "aarch64"
git-tree-sha1 = "ae1b4e6fbfeca725a1ef7dde97a6fda995540e7e"
os = "macos"

    [[Typst.download]]
    sha256 = "74685f7d67d6ff39c98e7b9654a16dca8a78c12de7a10cec46877135ffc903a2"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.13.0+0/Typst.v0.13.0.aarch64-apple-darwin.tar.gz"
[[Typst]]
arch = "aarch64"
git-tree-sha1 = "ef8a2d240f1e49cc5fd37420a81cc7825b5b2578"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "78d560ad286da463f92bfa936e5d47ba466c74ddbc82037e721d98a922ee59fb"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.13.0+0/Typst.v0.13.0.aarch64-linux-gnu.tar.gz"
[[Typst]]
arch = "aarch64"
git-tree-sha1 = "064c205f84c3276003002f2e30351245f2c53e9d"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "e1a01722f4f7b7b006a2e8544fbe0fd91f0ba27b7bca46d439e5ed0ceb67f212"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.13.0+0/Typst.v0.13.0.aarch64-linux-musl.tar.gz"
[[Typst]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c05e137d5db605785ae7bfe9920c5f9ca3bd9e19"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "e7d32c5d67cd86d40ca8ec8e7058d6127f7f3532f6163fab1251b1caca44e77f"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.13.0+0/Typst.v0.13.0.armv6l-linux-gnueabihf.tar.gz"
[[Typst]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8c45ff143555f6de45284377794db7297e42e622"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "fc0dc9e79b8b0c2f6ca828f9f4f00a5f81bfa27e8e93e5efbf57fe1d3bdd6eec"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.13.0+0/Typst.v0.13.0.armv6l-linux-musleabihf.tar.gz"
[[Typst]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8928239be1f92b791fcfb94b18874b9e9ab7b555"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "fccd31e8328aef6f950eb1285c75d35e2337f57f6b5dc3490c937eb44ee9de14"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.13.0+0/Typst.v0.13.0.armv7l-linux-gnueabihf.tar.gz"
[[Typst]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e36944bdbb8a41d61b40b7b68ec9846d64dd52af"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "419daffe363576f354a1bbf20a058c1af36432b1f332e04a46ef358f9efcf3d4"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.13.0+0/Typst.v0.13.0.armv7l-linux-musleabihf.tar.gz"
[[Typst]]
arch = "i686"
git-tree-sha1 = "fbd30b3208b84b72aa1cf1c1c8938a82bfa7fe7d"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "6c8a12b0f25893f45bf776d8d55f9585628f5c735510be23f745c2f44d57df0b"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.13.0+0/Typst.v0.13.0.i686-linux-gnu.tar.gz"
[[Typst]]
arch = "i686"
git-tree-sha1 = "19e6ae661ef7ee558d61b63bca4c12d21ebf382e"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "815b853fe671aa09a52fcc1340a4c59f1ec19e275d1d08b0821e7ca3a9173000"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.13.0+0/Typst.v0.13.0.i686-linux-musl.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "26487a9e6471b4a30e1f481db9e9ceaa8ca7a08b"
os = "macos"

    [[Typst.download]]
    sha256 = "7ac2316ecdd01133bc4268868401066646b6fbe30689328f4ee93f556bbfed0d"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.13.0+0/Typst.v0.13.0.x86_64-apple-darwin.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "7581f2451f6ad920093e325da4c8703c4dade4dc"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "76d890553febe56bcf8372add13c7f43b7efd50dc6385e86fe26dad354cc1d44"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.13.0+0/Typst.v0.13.0.x86_64-linux-gnu.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "27fa9870674d28b3c116e3f17a99eeb5b254148f"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "a45890168e7cdaba2ae1cecd3cee7ea1ea2e53ade5d3940f7645dd81cf8d2acc"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.13.0+0/Typst.v0.13.0.x86_64-linux-musl.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "d4b9c2827da15a25b1a41e72e36d160a6b7118b4"
os = "freebsd"

    [[Typst.download]]
    sha256 = "28e7a96ba11b31cf403a7cc18e37195e3295f4f75ee6e5fffeaedc81b0ac01b0"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.13.0+0/Typst.v0.13.0.x86_64-unknown-freebsd.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "f084027eb1ff2ef01bc85854410dcfe68a30d06c"
os = "windows"

    [[Typst.download]]
    sha256 = "5233dd57b7468180b6fabfaec336bb1a1ab8c653ac61e7027fb3b4bb85cd9afb"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.13.0+0/Typst.v0.13.0.x86_64-w64-mingw32.tar.gz"
