[[Typst]]
arch = "aarch64"
git-tree-sha1 = "e7f74006fddcb5829c34d454b149616010e52395"
os = "macos"

    [[Typst.download]]
    sha256 = "f1219de505cb5b5073570828b846b86074c24b7a93c0d5a54462ff8f5e2733a4"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.2.0+0/Typst.v0.2.0.aarch64-apple-darwin.tar.gz"
[[Typst]]
arch = "aarch64"
git-tree-sha1 = "e1494dbe0b7b9f0f5cb6bcc38f57cb52c838bd6c"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "b5683c0a6ac6398977bff6dea588f5684fd9a1a8b574581d91b8ac77bb229e95"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.2.0+0/Typst.v0.2.0.aarch64-linux-gnu.tar.gz"
[[Typst]]
arch = "aarch64"
git-tree-sha1 = "65b8a7f9a2e70cc05134cd0095e6aeca07a41715"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "ec6f1491b364cf6831ac3fa5495f99bf56b44386be666516673d446f4a582750"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.2.0+0/Typst.v0.2.0.aarch64-linux-musl.tar.gz"
[[Typst]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e7d02adfd67641d944344f715cafc5be930467c9"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "9d949f3eabef367e799615bd5324565f0b4f7f0b079933c8126a77516d1514b8"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.2.0+0/Typst.v0.2.0.armv6l-linux-gnueabihf.tar.gz"
[[Typst]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ec479d35e2b270c17c2a07da7ec6b7b1387f2b8b"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "e1fb3b98e8b5cd4dfd3d36758c01eb359fb6cd29e9e6c00657fa0b4a14a9e8ed"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.2.0+0/Typst.v0.2.0.armv6l-linux-musleabihf.tar.gz"
[[Typst]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "87c88bb78f5888f1b6311cde2f6975c669604942"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "cb4f172741090891d72bea9bc905fd7a32898ceae6e4cc2c2c063ceb595603ae"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.2.0+0/Typst.v0.2.0.armv7l-linux-gnueabihf.tar.gz"
[[Typst]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c03cbc3adfc27cd69deeca93984eef8f536c1610"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "71344b7740930a9c0d9369879a5eca1f42446c0c6dc66988761b1e6da971c526"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.2.0+0/Typst.v0.2.0.armv7l-linux-musleabihf.tar.gz"
[[Typst]]
arch = "i686"
git-tree-sha1 = "ffdf6bfbcd57f5ae1adb3ef10515e22cb36b1530"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "948293898e8ab66f5f70c072a6ff0ab5d41941393c06a2a0bfe91d46cd3a4af7"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.2.0+0/Typst.v0.2.0.i686-linux-gnu.tar.gz"
[[Typst]]
arch = "i686"
git-tree-sha1 = "2ce46b8e58fc3ac2a4727c5b1c60671daa6e144d"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "b20cfe0fa6d04d5ed9a32d56f13cfcc3b31dcf5f59f00de4a2ac4dd242e901b6"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.2.0+0/Typst.v0.2.0.i686-linux-musl.tar.gz"
[[Typst]]
arch = "powerpc64le"
git-tree-sha1 = "7b604e0689b87e9a23286b9ab3e48e372124a0ee"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "4ca5ea8aea3121f122433bd45da28b790d12242fd55dea1c212246165c99c283"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.2.0+0/Typst.v0.2.0.powerpc64le-linux-gnu.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "c3ca0104f0c4e0327a63f250af9eebe52ea11914"
os = "macos"

    [[Typst.download]]
    sha256 = "b5dc08f41e7f6378fbbc382aba2e15891e0c94be95c30a0afc5bbab6d7cbbc09"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.2.0+0/Typst.v0.2.0.x86_64-apple-darwin.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "56b6c5bbc7e0a805de3550a609c7a9b105025089"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "907f89225752fb51f1ef784c6773ba6aac953d91cb6f4fd55555d4908adfd0d0"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.2.0+0/Typst.v0.2.0.x86_64-linux-gnu.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "d22d6c14c7e642942df10d57d7dcdde0234e2dcd"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "1a26c789605f3a8643bd6d677c8e8862ac02b98ae048b1b371bc00c6684b081d"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.2.0+0/Typst.v0.2.0.x86_64-linux-musl.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "4b632f7d88fedf35b9bad6a61ce7008025460b95"
os = "freebsd"

    [[Typst.download]]
    sha256 = "758b5f72e7eba4e89007562aabb58953653b0cdcf8ff63120a385b9954a13a75"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.2.0+0/Typst.v0.2.0.x86_64-unknown-freebsd.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "237e456a157000114809c462daea5be09f137ceb"
os = "windows"

    [[Typst.download]]
    sha256 = "79af5f0d2e94954c67c20d8a724501ad0c93983f0dc21fc724a85cb905cf08d0"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.2.0+0/Typst.v0.2.0.x86_64-w64-mingw32.tar.gz"
