[[Typst]]
arch = "aarch64"
git-tree-sha1 = "4f48e43d3ab3f6ca886f9666ad81814d483bed37"
os = "macos"

    [[Typst.download]]
    sha256 = "b64d88552b78822366b2f80e914319aa8f9625ff27668e29d89858af4c5621cc"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.8.0+0/Typst.v0.8.0.aarch64-apple-darwin.tar.gz"
[[Typst]]
arch = "aarch64"
git-tree-sha1 = "090523dda8adbd246c629aa2afd6223878b5430d"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "9edcd466df895349653358daabecb90c8dd3b13a12f064d7b5e6761229f348da"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.8.0+0/Typst.v0.8.0.aarch64-linux-gnu.tar.gz"
[[Typst]]
arch = "aarch64"
git-tree-sha1 = "80345535ed477e95ab0719d99a8aea71203797c2"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "641910871bb1ea15e8992b51cadbba0fa1418667d7c446bc4bd55af5f6159d0b"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.8.0+0/Typst.v0.8.0.aarch64-linux-musl.tar.gz"
[[Typst]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ba4095f3bab8790204508d541a60df457b4e9572"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "2f1bbedebebfe623890479550f93860c6a4ff038417b76ea902280b253fab048"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.8.0+0/Typst.v0.8.0.armv6l-linux-gnueabihf.tar.gz"
[[Typst]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "50c3c38c2bdde5720e5cd54fb756e9c2a40b2d3d"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "ab2329c39227890401097136f84446f5f60858a667ca6702cbd037eb23a3cd1c"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.8.0+0/Typst.v0.8.0.armv6l-linux-musleabihf.tar.gz"
[[Typst]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "90f4acab16fda88671f532e343de219d8dfde479"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "8030161dc42f9a3d690c08b52f4e4d272a483242f4d86b67903951dd289af301"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.8.0+0/Typst.v0.8.0.armv7l-linux-gnueabihf.tar.gz"
[[Typst]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "468e65b676d3ab560357276cac55585f91df0fc4"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "b036662ea2c44c975290a06836b62e1eeef9dff2659aa1326a2509708afcf971"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.8.0+0/Typst.v0.8.0.armv7l-linux-musleabihf.tar.gz"
[[Typst]]
arch = "i686"
git-tree-sha1 = "961b1f804f3e941b13d23122ebe1f3ee0b49ad28"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "73d869b3eabc5e3cff98bb22f9b80bd180a42b5cc5dae9ce6fc70afa9e8fe3bf"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.8.0+0/Typst.v0.8.0.i686-linux-gnu.tar.gz"
[[Typst]]
arch = "i686"
git-tree-sha1 = "a6b11876659bbb10ca17598a1357c8906a4d68bc"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "8bc3be6df5c122518827004af69d8d6dda1a81556f93c6a5399f612672567951"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.8.0+0/Typst.v0.8.0.i686-linux-musl.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "a6c19fcb00a02cc45a81bff69c89377a6cc689b0"
os = "macos"

    [[Typst.download]]
    sha256 = "3611347728986d462c32811ff717986380caf28568b8a173c1d0dacb4db03adb"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.8.0+0/Typst.v0.8.0.x86_64-apple-darwin.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "720ae789f27595b86503d1398943333bb9e78f45"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "85d46b4efdaf6e56e1cad6064a31030aaf2e06e000c46ef0b95be45af67d95ca"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.8.0+0/Typst.v0.8.0.x86_64-linux-gnu.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "dc7453b039efc8abc242f0b8db7f44238a74d580"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "02a13fa2877cfa0b0bd8a4be865bb30a6b81cb76af06a3f1480ec9a97440a907"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.8.0+0/Typst.v0.8.0.x86_64-linux-musl.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "87dcab4305dec00d3a4caa6340c5f63d214ee034"
os = "freebsd"

    [[Typst.download]]
    sha256 = "704fac453d4d070e53ae99c7c9381f17b3ee63f813876c848dfe451bf066f5d9"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.8.0+0/Typst.v0.8.0.x86_64-unknown-freebsd.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "1ad06ae3968b00e41193004ee28354c86a4fdf6b"
os = "windows"

    [[Typst.download]]
    sha256 = "35727ad584731b4ea7081bf8610f8bd7cd9ce7d2d0c8797cf53740022f35ce6e"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.8.0+0/Typst.v0.8.0.x86_64-w64-mingw32.tar.gz"
