[[Typst]]
arch = "aarch64"
git-tree-sha1 = "264e67608b172a3064e2c66378154aaaa5572ffd"
os = "macos"

    [[Typst.download]]
    sha256 = "3d50d7ee344ed0538174b899a9a16924d857e8fb696a0a3e097dabaf3224f089"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.13.1+0/Typst.v0.13.1.aarch64-apple-darwin.tar.gz"
[[Typst]]
arch = "aarch64"
git-tree-sha1 = "a8bcd7e7635c25292343b31aaa6a0f2c4557993b"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "24afaab247238caddab35407f54593511b2227f00822841424501150c6898d50"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.13.1+0/Typst.v0.13.1.aarch64-linux-gnu.tar.gz"
[[Typst]]
arch = "aarch64"
git-tree-sha1 = "aef1685d795b5ef101506620ca05d327494b9dbf"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "6caa1c86fa1314f1ac50f6e652fa3e94b5f76eba7bb9eeb22cb729255509773d"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.13.1+0/Typst.v0.13.1.aarch64-linux-musl.tar.gz"
[[Typst]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d15304151bc3b41ca921cb3d5e5faed3db9abe38"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "759909a25d564741486015e3034c1f30e68cafceb761df3ab0c863a06e112126"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.13.1+0/Typst.v0.13.1.armv6l-linux-gnueabihf.tar.gz"
[[Typst]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8dd560a1c2eac1817fca01b9e9882f61128e77d4"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "a880fa68513eb663c86de1253207fa8850e6112407102fde3bcc44ef3f0437a2"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.13.1+0/Typst.v0.13.1.armv6l-linux-musleabihf.tar.gz"
[[Typst]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7993d7ca87d446cbb1e85b6cab4bf6e9ffcbeb7e"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "9a989c3e57bb84b89e2a4aab0d1ac75bd37b6fa237428e16275b3c9d30c63d2c"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.13.1+0/Typst.v0.13.1.armv7l-linux-gnueabihf.tar.gz"
[[Typst]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b1c7be8d530e660f9c10bc77f415b59db7c214ee"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "016329b873ecf6f6fa1c587b2502fe72d95b6668e5318a04c9624ba297736c64"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.13.1+0/Typst.v0.13.1.armv7l-linux-musleabihf.tar.gz"
[[Typst]]
arch = "i686"
git-tree-sha1 = "76df8a939593569e7cff01cd9c0aff6198336fae"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "5d8c96b472ac37c565e3fdf48588240280c76eee80cc9b8bc5462e64970c1d55"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.13.1+0/Typst.v0.13.1.i686-linux-gnu.tar.gz"
[[Typst]]
arch = "i686"
git-tree-sha1 = "f77d1f57fef15771496d91c3976b0ad5f7355e3d"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "b4cfea85768677d5b338e264ca15477bd3d44e69a528fad9762e561b2c0fdc52"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.13.1+0/Typst.v0.13.1.i686-linux-musl.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "a04d0987d56ddb701d29c1423f30b5fbb7eb9974"
os = "macos"

    [[Typst.download]]
    sha256 = "d2640e9a93b20dd7f0f96f217c4492898e5225ca4ba4a4f97667e8b1fc926511"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.13.1+0/Typst.v0.13.1.x86_64-apple-darwin.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "f7cad9ad138b7c66f86d0e17811847457b80f6ff"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "c8cb27be147d84b13d9c590d14290098705a849b333c2c41b0ddae76f322f495"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.13.1+0/Typst.v0.13.1.x86_64-linux-gnu.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "327dfb9a3c96e7bb816061ca80c83f218d86fc76"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "2e4f202b9a5a1c240ab3f3496d58688738000846bc577eb85409abdad0a4a73d"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.13.1+0/Typst.v0.13.1.x86_64-linux-musl.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "e9806438680533a6fa04af83054f3920ba287be2"
os = "freebsd"

    [[Typst.download]]
    sha256 = "2261fe4053e2be8c0a212ccfe470e4634aacf1c0611e85b4e70f7b8141a6e660"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.13.1+0/Typst.v0.13.1.x86_64-unknown-freebsd.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "2df41e5d1c143ba1c47aa52fc5b160561d720afc"
os = "windows"

    [[Typst.download]]
    sha256 = "650fe50d4a50d6f0191bda77170565e8c1bb2692ade6e81f1d05a9779bd7409d"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.13.1+0/Typst.v0.13.1.x86_64-w64-mingw32.tar.gz"
