[[Typst]]
arch = "aarch64"
git-tree-sha1 = "580fb1c3925be6ddace0c28438aae2782b63a31c"
os = "macos"

    [[Typst.download]]
    sha256 = "2d149e93053658ed250da8b1225d8dde7c5b31f3a57d124099f2afd17399f484"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.11.0+0/Typst.v0.11.0.aarch64-apple-darwin.tar.gz"
[[Typst]]
arch = "aarch64"
git-tree-sha1 = "4b068d270ed2598c617f55419dcb1cb370aa5511"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "f31a5c622a991a1e8dfda3702b8b61349363dd755507f7e2b2c6359c1ee68c24"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.11.0+0/Typst.v0.11.0.aarch64-linux-gnu.tar.gz"
[[Typst]]
arch = "aarch64"
git-tree-sha1 = "7ec11075bf50cd0ed16c660d126dad8ee60dbb34"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "9e57562e91d3786552bcccec9c197e6893671d3b4964d9f8f4c9da7dcf17fb47"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.11.0+0/Typst.v0.11.0.aarch64-linux-musl.tar.gz"
[[Typst]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b327c7f7db26882a17eb77bd4b459686c46a8eda"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "85c0606aef84570c75b6401ba7cd33c90d0fd1a96a7b752f40f92afc6d52e227"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.11.0+0/Typst.v0.11.0.armv6l-linux-gnueabihf.tar.gz"
[[Typst]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4953879cc3d2f15b083255350f05a67c3e7d3a76"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "e7dad0f60e867abcf9cc940ec0ecdb2a267424bb41f0f7d76cdb2d9f876d5fb4"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.11.0+0/Typst.v0.11.0.armv6l-linux-musleabihf.tar.gz"
[[Typst]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ff381ea1f8d6731a3f2d64327765b67d2498c247"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "b65e30a0db96d7135ad85f30708d144770fdf42576d850413300ab80f16e539d"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.11.0+0/Typst.v0.11.0.armv7l-linux-gnueabihf.tar.gz"
[[Typst]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "110451c9d375ac63b2f51096875260d26ad3cfb3"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "cb758eb20fb9d625401ba9623ab3e926bc845bd8ec184eec85012192623a6cbd"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.11.0+0/Typst.v0.11.0.armv7l-linux-musleabihf.tar.gz"
[[Typst]]
arch = "i686"
git-tree-sha1 = "926c60a4d99ad1b71c2519f64855d51bca5f1d48"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "11a1a41f4d919a7fa502a529c1b5b74a8b3a626afdeabbfc1f12b9248b991e95"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.11.0+0/Typst.v0.11.0.i686-linux-gnu.tar.gz"
[[Typst]]
arch = "i686"
git-tree-sha1 = "faed20b6deb2f83e05a9780fbde4514e74a94f33"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "ca46ac932cb6a152b451c86625345a5881936415e9fd4caa581a24214b005398"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.11.0+0/Typst.v0.11.0.i686-linux-musl.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "164a890c8974bf399dd67e14b12035cbbebd1130"
os = "macos"

    [[Typst.download]]
    sha256 = "dc900a5f557c81b49452420314a15ac824a9ebfd4d0e40a60d61a12925d6654c"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.11.0+0/Typst.v0.11.0.x86_64-apple-darwin.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "6a6b0323786c846a9713112e4947b8a95ded2c9d"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "45404c7a4a58b549a66b814abdf37e64b431d3116d1763c346d0eff3a441e009"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.11.0+0/Typst.v0.11.0.x86_64-linux-gnu.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "e5860994d594f447b9aebcf6f63df24906317e79"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "081d79a651a0400d77ee73d64416cbab101fcfd977e085f6628e3eddc0061f2d"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.11.0+0/Typst.v0.11.0.x86_64-linux-musl.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "a8cb4152323f1d8378ef4d832e51aef3eb18f4b9"
os = "freebsd"

    [[Typst.download]]
    sha256 = "e76496cf5f1fcc32c85540afc4fb37424c14ffa62dc9f82d604ac9fba2180ad7"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.11.0+0/Typst.v0.11.0.x86_64-unknown-freebsd.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "c344cc600562ed64ac00dc4ab5e14436ca3712eb"
os = "windows"

    [[Typst.download]]
    sha256 = "93cc0b6722f86d5dd2fd0e05c8f742d107f474a3217d55ec5bf8921af1d65859"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.11.0+0/Typst.v0.11.0.x86_64-w64-mingw32.tar.gz"
