[[Typst]]
arch = "aarch64"
git-tree-sha1 = "f55cf2a7e50e4b7d54a57354eb1608f1d63baf64"
os = "macos"

    [[Typst.download]]
    sha256 = "1175a09241f87d02d98964c05ae4bd446da53e2cc6af0ca104744730794eaea5"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.10.0+0/Typst.v0.10.0.aarch64-apple-darwin.tar.gz"
[[Typst]]
arch = "aarch64"
git-tree-sha1 = "6720906e2573ebe7bd80aa0e978ee16381a68fd4"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "c51af16de3e215f9b828e906eb7d4882a9487000326eb056d598cc39f2cde95f"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.10.0+0/Typst.v0.10.0.aarch64-linux-gnu.tar.gz"
[[Typst]]
arch = "aarch64"
git-tree-sha1 = "0ef25d4f619b5d5cb7a3e00555cf3b2df124298d"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "c9fdbbeb1e157bab86a56968f3895255837966ea54bef27e448d1f6b44155deb"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.10.0+0/Typst.v0.10.0.aarch64-linux-musl.tar.gz"
[[Typst]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "34a5d97218394d8c7bf85c71d2e828ca05b23779"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "b9355b1b85723d395c851d035fb27d50b4d5a54c4e8f2037379d57484f7d55e3"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.10.0+0/Typst.v0.10.0.armv6l-linux-gnueabihf.tar.gz"
[[Typst]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "24ee7a7dc06124981da0d8a3488c16692934780c"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "effa6161cbf4a418e7284be9563fd2998e1b22e740058e6bd663fa7dd77e8f6e"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.10.0+0/Typst.v0.10.0.armv6l-linux-musleabihf.tar.gz"
[[Typst]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "189733eb472622e7a3568aba0afd49680ad27014"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "7e8bd626d4900b4ab961ac860a06ceb71174a4da0c4220842a6287bfeec81cee"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.10.0+0/Typst.v0.10.0.armv7l-linux-gnueabihf.tar.gz"
[[Typst]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0367374e240b25a412a48fa6bc309ac6313c9dd9"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "3868385ce11fd8b84555e37021176e22191f90a091a4312dadc027b3898f0b7c"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.10.0+0/Typst.v0.10.0.armv7l-linux-musleabihf.tar.gz"
[[Typst]]
arch = "i686"
git-tree-sha1 = "8f945aaff65996f5c2e67a21cf5cf995b1237c03"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "6e00b2dd90613c936ea2b92107c392eb24fa2bb1923786d8f731d9adf2485e26"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.10.0+0/Typst.v0.10.0.i686-linux-gnu.tar.gz"
[[Typst]]
arch = "i686"
git-tree-sha1 = "3fec4968659f8110fa0854edbe373e85f256608f"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "6fb924a67b8b0c534fa957a3a8274e1cfd7000e8f10fe6f4e718503d0ea60cd9"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.10.0+0/Typst.v0.10.0.i686-linux-musl.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "40de0e7f02d45550a1e1403a5d41f64fe5202956"
os = "macos"

    [[Typst.download]]
    sha256 = "1a0a1b3fa71b9cb5cedccdb96c67c7d066d1a26f2e582a1fe5581d86b68baa9e"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.10.0+0/Typst.v0.10.0.x86_64-apple-darwin.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "fa23df1fa1f5f708e814b359b744c95275512031"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "0b5b303534b5632d5632ac3226f87e6b127e2a56561a3ba45e3694b48fde0d66"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.10.0+0/Typst.v0.10.0.x86_64-linux-gnu.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "8070f62c773c39b556f824478632f224daaa8943"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "253dbeb39fc1d77169df983068c0b37d0de1c54cf915f263c4ba876bbf542724"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.10.0+0/Typst.v0.10.0.x86_64-linux-musl.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "6287ea4dc96f6a541403dfad6e351e165f52e556"
os = "freebsd"

    [[Typst.download]]
    sha256 = "2b9bd2a4229e409031934b0ca13fb3cb632bf785c52b6a068a33f0219b6e4ee7"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.10.0+0/Typst.v0.10.0.x86_64-unknown-freebsd.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "474adf7966a797d140929163f7c15e489795c61e"
os = "windows"

    [[Typst.download]]
    sha256 = "07bd7036cd642a366b86f10f5a738c3c71977452f26207a419f3801f5364a4c7"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.10.0+0/Typst.v0.10.0.x86_64-w64-mingw32.tar.gz"
