[[Typst]]
arch = "aarch64"
git-tree-sha1 = "3743a25b0b39a467dce2e512e93b9b9c3b57a3cf"
os = "macos"

    [[Typst.download]]
    sha256 = "c53bf0c0b80afd4c0f3fc1339b9f55fcdc8d0033839f2d6069d15485a148d116"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.3.0+0/Typst.v0.3.0.aarch64-apple-darwin.tar.gz"
[[Typst]]
arch = "aarch64"
git-tree-sha1 = "247a5b2053d74caacadac3bcd833af85171ae477"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "403fb9056ab5b7d04a6c8212765c5b8b6aba5d74dbf1ecffaeab6adae237be30"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.3.0+0/Typst.v0.3.0.aarch64-linux-gnu.tar.gz"
[[Typst]]
arch = "aarch64"
git-tree-sha1 = "5aca81c5fbea780abcdb4efeab3a18610f0c4096"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "8db2c77bb73fe1fd57d4757562df4b72c32c7f4045f04fb7902e2861d0354cd0"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.3.0+0/Typst.v0.3.0.aarch64-linux-musl.tar.gz"
[[Typst]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7bcd825a4a1d05ddabad0b3eaebacc42d699edd6"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "b269bbe7774c99bb8b9c0c97d4a6abc0f969d76a115cc7625a0ec3cea6863b06"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.3.0+0/Typst.v0.3.0.armv6l-linux-gnueabihf.tar.gz"
[[Typst]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5bfb9864662c6d6a2417cabf2f759c1d77322d36"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "7f65b119964abb77d4582b1efd8f491a186f0e3838432fd6f8be804c66c57950"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.3.0+0/Typst.v0.3.0.armv6l-linux-musleabihf.tar.gz"
[[Typst]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ae2559d9156036500c076f4f2f5e439f3a776aa9"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "aa3dda838293c570e9bedb9eee15493362b88fcb469c091f15b0598e8d791194"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.3.0+0/Typst.v0.3.0.armv7l-linux-gnueabihf.tar.gz"
[[Typst]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3e091eb112ff224ac0696b0b41f616f3265384b4"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "396ecf130c000364e72fbb1e42eeec20140c3ab86e146dda387a864989fbe8f8"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.3.0+0/Typst.v0.3.0.armv7l-linux-musleabihf.tar.gz"
[[Typst]]
arch = "i686"
git-tree-sha1 = "50cc9ea752167a9cfb178a81b66fdd8062fbf25d"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "19048681a4a8e67381697c3295552ca582255a093fddad5d1177cc21b06e6fa6"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.3.0+0/Typst.v0.3.0.i686-linux-gnu.tar.gz"
[[Typst]]
arch = "i686"
git-tree-sha1 = "f7054818932f374a842ad8f8c5847e78061ca6df"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "6835916f9aba65634d7df343b247691afabc7d3c1c34ff38d21cd2ad5760afbf"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.3.0+0/Typst.v0.3.0.i686-linux-musl.tar.gz"
[[Typst]]
arch = "powerpc64le"
git-tree-sha1 = "9976213ac43addd1b6f0443b04f975fb94ec6e5d"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "61ba20f0b2c46086f7427e1c06dfffb18fcb7ab11594ce5e409b726339415e5c"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.3.0+0/Typst.v0.3.0.powerpc64le-linux-gnu.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "055d5d66229dec4d78d6306d9ef91939b0577a77"
os = "macos"

    [[Typst.download]]
    sha256 = "2c1b4799b35e51140a1d822636965ee6adf5eb5fe7697b8767147441f524b9f6"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.3.0+0/Typst.v0.3.0.x86_64-apple-darwin.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "cb5543189ca47036ec881fdf58de37b09aba26d1"
libc = "glibc"
os = "linux"

    [[Typst.download]]
    sha256 = "9daf3b957b9e26c9eab7b150a35cd0e0efbffd43600c4a3a4ca168b13312e59f"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.3.0+0/Typst.v0.3.0.x86_64-linux-gnu.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "ed4e78abd2feb45fcdf22def2d2f4552d708dcb0"
libc = "musl"
os = "linux"

    [[Typst.download]]
    sha256 = "b6588ba7bf58b05387fd32bb2aa1ee1086dc76ad2e02401ae3283627f2ec381b"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.3.0+0/Typst.v0.3.0.x86_64-linux-musl.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "152c1288fb0c11f94ff74e7f03c09ca6a0834216"
os = "freebsd"

    [[Typst.download]]
    sha256 = "aa9eff263b48909a73b30f3b5157c671e0400700288df511099a6da634bd97d8"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.3.0+0/Typst.v0.3.0.x86_64-unknown-freebsd.tar.gz"
[[Typst]]
arch = "x86_64"
git-tree-sha1 = "7cf8ed6bbbfe90e66a789986f07cfd2617782f39"
os = "windows"

    [[Typst.download]]
    sha256 = "633b48694871e0f052996d8ee0f6aae2e4f48826854cf0246c443853cf78887b"
    url = "https://github.com/JuliaBinaryWrappers/Typst_jll.jl/releases/download/Typst-v0.3.0+0/Typst.v0.3.0.x86_64-w64-mingw32.tar.gz"
